[profile.default]
src = "src"
out = "out"
libs = ["lib"]
no-storage-caching = true
via_ir = true

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
